linters-settings:
  wrapcheck:
    ignorePackageGlobs:
      - github.com/vilsol/oshabi/*

linters:
  disable-all: true
  enable:
    - deadcode
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - structcheck
    # - typecheck
    - unused
    - varcheck
    - bidichk
    - contextcheck
    - durationcheck
    - errorlint
    - goconst
    - goimports
    - revive
    - ifshort
    - misspell
    - prealloc
    - whitespace
    - wrapcheck