// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetListings() {
  return window['go']['main']['App']['GetListings']();
}

export function SetLeague(arg1) {
  return window['go']['main']['App']['SetLeague'](arg1);
}

export function SetName(arg1) {
  return window['go']['main']['App']['SetName'](arg1);
}

export function SetStream(arg1) {
  return window['go']['main']['App']['SetStream'](arg1);
}

export function UpdatePricing() {
  return window['go']['main']['App']['UpdatePricing']();
}

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function Read() {
  return window['go']['main']['App']['Read']();
}

export function SetShortcut(arg1) {
  return window['go']['main']['App']['SetShortcut'](arg1);
}

export function Calibrate() {
  return window['go']['main']['App']['Calibrate']();
}

export function GetDisplayCount() {
  return window['go']['main']['App']['GetDisplayCount']();
}

export function SetDisplay(arg1) {
  return window['go']['main']['App']['SetDisplay'](arg1);
}

export function SetLanguage(arg1) {
  return window['go']['main']['App']['SetLanguage'](arg1);
}

export function SetListingCount(arg1, arg2, arg3) {
  return window['go']['main']['App']['SetListingCount'](arg1, arg2, arg3);
}

export function Clear() {
  return window['go']['main']['App']['Clear']();
}

export function GetLanguages() {
  return window['go']['main']['App']['GetLanguages']();
}

export function SetPrice(arg1, arg2) {
  return window['go']['main']['App']['SetPrice'](arg1, arg2);
}

export function Copy() {
  return window['go']['main']['App']['Copy']();
}
