// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {types} from '../models';

export function Calibrate():void;

export function Clear():Promise<boolean>;

export function Copy():void;

export function GetConfig():Promise<main.ConvertedConfig>;

export function GetListings():Promise<Array<types.ParsedListing>>;

export function SetLeague(arg1:string):void;

export function SetName(arg1:string):void;

export function SetPrice(arg1:string,arg2:string):void;

export function SetStream(arg1:boolean):void;

export function UpdatePricing():void;

export function Read():Promise<boolean>;

export function SetListingCount(arg1:string,arg2:number,arg3:number):void;
