name: push

permissions: read-all

on: [push, pull_request]

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.18

      - name: Check out code
        uses: actions/checkout@v2

      - name: Tidy
        run: go mod tidy -compat=1.17

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          skip-pkg-cache: true
          skip-build-cache: true
          args: --timeout 5m

  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.18

      - name: Check out code
        uses: actions/checkout@v2

      - name: Install Dependencies
        run: |
          sudo add-apt-repository -y ppa:alex-p/tesseract-ocr-devel
          sudo apt -y install tesseract-ocr libtesseract-dev libgtk-3-dev libwebkit2gtk-4.0-dev build-essential pkg-config upx libx11-dev xorg-dev libxtst-dev libpng++-dev xcb libxcb-xkb-dev x11-xkb-utils libx11-xcb-dev libxkbcommon-x11-dev libxkbcommon-dev xsel xclip

      - name: Clone GoCV
        run: git clone https://github.com/hybridgroup/gocv.git

      - name: Install OpenCV
        run: cd gocv && make install && cd .. && rm -rf gocv

      - name: Tidy
        run: go mod tidy -compat=1.17

      - name: Test
        run: |
          mkdir -p frontend/dist/
          touch frontend/dist/hello
          go test -v ./...

  linux:
    name: Build (Linux)
    runs-on: ubuntu-20.04
    needs:
      - lint
      - test
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18

      - name: Install Dependencies
        run: |
          sudo add-apt-repository -y ppa:alex-p/tesseract-ocr-devel
          sudo apt -y install tesseract-ocr libtesseract-dev libgtk-3-dev libwebkit2gtk-4.0-dev build-essential pkg-config upx libx11-dev xorg-dev libxtst-dev libpng++-dev xcb libxcb-xkb-dev x11-xkb-utils libx11-xcb-dev libxkbcommon-x11-dev libxkbcommon-dev xsel xclip

      - name: Install pnpm
        uses: pnpm/action-setup@v2.2.1
        with:
          version: 7
          run_install: |
            - cwd: frontend

      - name: Clone GoCV
        run: git clone https://github.com/hybridgroup/gocv.git

      - name: Install OpenCV
        run: cd gocv && make install

      - name: Install Wails
        run: |
          go install github.com/wailsapp/wails/v2/cmd/wails@latest
          wails doctor

      - name: Build
        run: wails build -v 2 -debug

      - name: Archive artifacts
        uses: actions/upload-artifact@v3
        with:
          name: linux
          path: build/bin/oshabi

  windows:
    name: Build (Windows)
    runs-on: windows-latest
    needs:
      - lint
      - test
    defaults:
      run:
        shell: msys2 {0}
    steps:
      - uses: msys2/setup-msys2@v2
        with:
          msystem: mingw64
          update: true
          install: >-
            git
            base-devel
            mingw-w64-x86_64-cmake
            mingw-w64-x86_64-toolchain
            mingw-w64-x86_64-tesseract-ocr
            mingw-w64-x86_64-tesseract-data-eng
            mingw-w64-x86_64-leptonica
            mingw-w64-x86_64-go
            mingw-w64-x86_64-nsis

      - name: Check out code
        uses: actions/checkout@v2

      - name: Clone GoCV
        run: git clone https://github.com/hybridgroup/gocv.git

      - name: Make fake path
        run: mkdir -p C:/src/gocv.io/x/gocv

      - name: Cache OpenCV
        id: cache-opencv
        uses: actions/cache@v3
        with:
          path: C:/opencv
          key: ${{ runner.os }}-opencv

      - name: Install OpenCV
        run: cd gocv && ./win_build_opencv.cmd
        env:
          GOPATH: "C:"

      - name: Install pnpm
        uses: pnpm/action-setup@v2.2.1
        with:
          version: 7
          run_install: |
            - cwd: frontend

      - name: Build frontend
        working-directory: frontend
        shell: cmd
        run: pnpm run build

      - name: Install Wails
        run: |
          export PATH=/usr/bin
          export PATH=$PATH:/bin
          export PATH=$PATH:/d/a/_temp/setup-msys2
          export PATH=$PATH:/c/opencv/build/bin
          export PATH=$PATH:/d/a/_temp/msys64/mingw64/bin
          export PATH=$PATH:/d/a/_temp/msys64/mingw64/include
          export PATH=$PATH:/c/Users/runneradmin/go/bin
          go env
          go install github.com/wailsapp/wails/v2/cmd/wails@latest
          wails doctor

      - name: Build
        run: |
          export PATH=/usr/bin
          export PATH=$PATH:/bin
          export PATH=$PATH:/d/a/_temp/setup-msys2
          export PATH=$PATH:/c/opencv/build/bin
          export PATH=$PATH:/d/a/_temp/msys64/mingw64/bin
          export PATH=$PATH:/d/a/_temp/msys64/mingw64/include
          export PATH=$PATH:/c/Users/runneradmin/go/bin
          wails build -v 2 -s -nsis -debug

      - name: Archive artifacts
        uses: actions/upload-artifact@v3
        with:
          name: windows
          path: build/bin/oshabi-amd64-installer.exe
